name: weather_with_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  anim_search_bar: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


